# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Assistant Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing. 


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 351)
        self.VoiceAssistantgif = QtWidgets.QLabel(Dialog)
        self.VoiceAssistantgif.setGeometry(QtCore.QRect(-4, 0, 471, 351))
        self.VoiceAssistantgif.setText("")
        self.VoiceAssistantgif.setPixmap(QtGui.QPixmap("../Users/HP/Downloads/Voice assistant UI.gif"))
        self.VoiceAssistantgif.setScaledContents(True)
        self.VoiceAssistantgif.setObjectName("VoiceAssistantgif")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 280, 121, 61))
        self.pushButton.setStyleSheet("font: 20pt \"Viner Hand ITC\";\n"
"color: rgb(85, 255, 255);\n"
"background-color:transparent\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 280, 121, 61))
        self.pushButton_2.setStyleSheet("font: 20pt \"Viner Hand ITC\";\n"
"color: rgb(85, 255, 255);\n"
"background-color:transparent\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "start"))
        self.pushButton_2.setText(_translate("Dialog", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
